export const styles = {
  container: {
    display: 'flex',
    height: '100vh',
    backgroundColor: '#f5f5f5',
  },
  mainContent: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '1rem',
    backgroundColor: '#fff',
    borderBottom: '1px solid #e0e0e0',
    boxShadow: '0 2px 4px rgba(0,0,0,0.1)',
  },
  backButton: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    padding: '0.5rem 1rem',
    backgroundColor: '#f0f0f0',
    border: 'none',
    borderRadius: '4px',
    cursor: 'pointer',
    transition: 'background-color 0.2s',
    color: '#333',
    fontSize: '0.9rem',
    '&:hover': {
      backgroundColor: '#e0e0e0',
    },
  },
  saveButton: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    padding: '0.5rem 1rem',
    backgroundColor: '#4CAF50',
    color: '#fff',
    border: 'none',
    borderRadius: '4px',
    cursor: 'pointer',
    transition: 'background-color 0.2s',
    fontSize: '0.9rem',
    '&:hover': {
      backgroundColor: '#45a049',
    },
    '&:disabled': {
      backgroundColor: '#cccccc',
      cursor: 'not-allowed',
    },
  },
  editorSection: {
    flex: 1,
    display: 'flex',
    padding: '1rem',
    gap: '1rem',
    overflow: 'hidden',
  },
  titleInput: {
    width: '100%',
    padding: '0.75rem',
    fontSize: '1.5rem',
    border: 'none',
    borderBottom: '2px solid #e0e0e0',
    marginBottom: '1rem',
    outline: 'none',
    backgroundColor: '#fff',
    borderRadius: '4px',
    '&:focus': {
      borderBottomColor: '#4CAF50',
    },
  },
  quillEditor: {
    flex: 1,
    backgroundColor: '#fff',
    borderRadius: '4px',
    boxShadow: '0 2px 4px rgba(0,0,0,0.1)',
    '& .ql-container': {
      height: 'calc(100% - 42px)',
      fontSize: '1rem',
    },
    '& .ql-editor': {
      padding: '1rem',
    },
  },
  sidebar: {
    width: '300px',
    backgroundColor: '#fff',
    borderLeft: '1px solid #e0e0e0',
    display: 'flex',
    flexDirection: 'column',
    overflow: 'auto',
  },
  sidebarSection: {
    padding: '1rem',
    borderBottom: '1px solid #e0e0e0',
  },
  sectionTitle: {
    fontSize: '1.1rem',
    fontWeight: 'bold',
    marginBottom: '0.75rem',
    color: '#333',
  },
  fileList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.5rem',
  },
  fileItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    padding: '0.75rem',
    backgroundColor: '#f5f5f5',
    borderRadius: '4px',
    transition: 'background-color 0.2s',
    '&:hover': {
      backgroundColor: '#e8e8e8',
    },
  },
  fileInfo: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    gap: '0.25rem',
  },
  fileName: {
    fontWeight: 'bold',
    color: '#333',
  },
  fileMeta: {
    fontSize: '0.8rem',
    color: '#666',
  },
  fileActions: {
    display: 'flex',
    gap: '0.5rem',
  },
  actionButton: {
    padding: '0.25rem',
    backgroundColor: 'transparent',
    border: 'none',
    cursor: 'pointer',
    color: '#666',
    transition: 'color 0.2s',
    '&:hover': {
      color: '#4CAF50',
    },
  },
  linkList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.5rem',
  },
  linkItem: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.25rem',
    padding: '0.75rem',
    backgroundColor: '#f5f5f5',
    borderRadius: '4px',
    transition: 'background-color 0.2s',
    '&:hover': {
      backgroundColor: '#e8e8e8',
    },
  },
  linkTitle: {
    fontWeight: 'bold',
    color: '#333',
  },
  linkUrl: {
    fontSize: '0.8rem',
    color: '#666',
    wordBreak: 'break-all',
  },
  linkActions: {
    display: 'flex',
    gap: '0.5rem',
    marginTop: '0.25rem',
  },
  chatSection: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    padding: '1rem',
  },
  chatMessages: {
    flex: 1,
    overflow: 'auto',
    display: 'flex',
    flexDirection: 'column',
    gap: '1rem',
    padding: '0.5rem',
  },
  chatMessage: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.25rem',
    padding: '0.75rem',
    backgroundColor: '#f5f5f5',
    borderRadius: '4px',
    transition: 'background-color 0.2s',
    '&:hover': {
      backgroundColor: '#e8e8e8',
    },
  },
  messageHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  messageSender: {
    fontWeight: 'bold',
    color: '#333',
  },
  messageTime: {
    fontSize: '0.8rem',
    color: '#666',
  },
  messageContent: {
    wordBreak: 'break-word',
    color: '#333',
  },
  messageActions: {
    display: 'flex',
    gap: '0.5rem',
    marginTop: '0.25rem',
  },
  chatInput: {
    display: 'flex',
    gap: '0.5rem',
    marginTop: '1rem',
    padding: '0.5rem',
  },
  messageInput: {
    flex: 1,
    padding: '0.75rem',
    border: '1px solid #e0e0e0',
    borderRadius: '4px',
    resize: 'none',
    fontSize: '0.9rem',
    '&:focus': {
      outline: 'none',
      borderColor: '#4CAF50',
    },
  },
  sendButton: {
    padding: '0.75rem 1.5rem',
    backgroundColor: '#4CAF50',
    color: '#fff',
    border: 'none',
    borderRadius: '4px',
    cursor: 'pointer',
    transition: 'background-color 0.2s',
    fontSize: '0.9rem',
    '&:hover': {
      backgroundColor: '#45a049',
    },
    '&:disabled': {
      backgroundColor: '#cccccc',
      cursor: 'not-allowed',
    },
  },
  loadingSpinner: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    height: '100%',
    color: '#666',
  },
  errorMessage: {
    color: '#f44336',
    textAlign: 'center',
    padding: '1rem',
    backgroundColor: '#ffebee',
    borderRadius: '4px',
    margin: '1rem',
  },
  modal: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.5)',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1000,
  },
  modalContent: {
    backgroundColor: '#fff',
    padding: '1.5rem',
    borderRadius: '4px',
    maxWidth: '500px',
    width: '100%',
    boxShadow: '0 4px 6px rgba(0,0,0,0.1)',
  },
  modalHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '1rem',
  },
  modalTitle: {
    fontSize: '1.2rem',
    fontWeight: 'bold',
    color: '#333',
    margin: 0,
  },
  modalClose: {
    backgroundColor: 'transparent',
    border: 'none',
    cursor: 'pointer',
    fontSize: '1.5rem',
    color: '#666',
    padding: '0.25rem',
    '&:hover': {
      color: '#333',
    },
  },
  modalBody: {
    marginBottom: '1.5rem',
    color: '#333',
  },
  modalFooter: {
    display: 'flex',
    justifyContent: 'flex-end',
    gap: '0.75rem',
  },
  confirmButton: {
    padding: '0.75rem 1.5rem',
    backgroundColor: '#4CAF50',
    color: '#fff',
    border: 'none',
    borderRadius: '4px',
    cursor: 'pointer',
    transition: 'background-color 0.2s',
    fontSize: '0.9rem',
    '&:hover': {
      backgroundColor: '#45a049',
    },
  },
  cancelButton: {
    padding: '0.75rem 1.5rem',
    backgroundColor: '#f44336',
    color: '#fff',
    border: 'none',
    borderRadius: '4px',
    cursor: 'pointer',
    transition: 'background-color 0.2s',
    fontSize: '0.9rem',
    '&:hover': {
      backgroundColor: '#d32f2f',
    },
  },
}; 